[env:waveshare-s3-eth]
extends = esp32s3_base
board = esp32-s3-devkitc-1
board_check = true
board_level = extra
board_build.partitions = default_16MB.csv
board_upload.flash_size = 16MB
board_build.arduino.memory_type = qio_opi

build_flags =
  ${esp32s3_base.build_flags}
  -D WAVESHARE_S3_ETH
  -D HAS_UDP_MULTICAST=1
  -D BOARD_HAS_PSRAM
  -D MESHTASTIC_EXCLUDE_BLUETOOTH=1
  -D MESHTASTIC_DISABLE_TRANSMIT_HISTORY_DISK=1
  -D ARDUINO_USB_CDC_ON_BOOT=1
  -I variants/esp32s3/waveshare-s3-eth

lib_ignore =
  Ethernet

lib_deps =
  ${esp32s3_base.lib_deps}
  # renovate: datasource=github-tags depName=ETHClass2 packageName=meshtastic/ETHClass2
  https://github.com/meshtastic/ETHClass2/archive/v1.0.0.zip
